version: '3.8'
services:
  jobswrapper:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target:/target
    environment:
      - DATA_AT_WORK_URL=http://api.dataatwork.org/v1